### ISSUE TITLE
Criar HTML base do website.

### ISSUE THREAD

**Issue by MajimbaV** [MajimbaV/IFPB_30_Anos---Mapa-Regional#3]
Montar o esqueleto da página em HTML, contendo os principais elementos, como navegação, ícones/logos, ou qualquer informação de texto ou visual que não necessariamente envolva a implementação do mapa interativo.

**Comment by DomHenriqueBR** [comment]
Algumas coisas não podemos fazer devido ao fato de estarem voltadas a estilização
